apiVersion: v1
kind: PersistentVolume
metadata:
  name: qcard-nfs-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 379a04bb07-rfc46.cn-shanghai.nas.aliyuncs.com
    path: /

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qcard-nfs-pvc
  namespace: qcard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
